### Get user
GET http://localhost:4000/api/users/


### Get all users
GET http://localhost:4000/api/users


### Create user
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "username": "test",
    "age": 23,
    "hobbies": ["reading", "writing", "coding"]
}

### Update user
PUT http://localhost:4000/api/users/
Content-Type: application/json

{
    "username": "update",
    "age": 25,
    "hobbies": ["changed"]
}

### Delete user
DELETE http://localhost:4000/api/users/


### Request to non-existent endpoints
GET http://localhost:4000/api/api2